### PR TITLE
Alternate mechanics

### PR DESCRIPTION
**Pull request by freeman-lab**
This PR tracks a reworking of the basic progress mechanics. It reflects lots of informal player testing, and studies of other games. I've had the following goals in mind, which I think we've all more or less agreed on, if not laid out formally.
- **Minimize frustration**. Rather than have many deaths and restarts within a single level, often with little prior notice, there should be one, clearly demarcated scenario in which you fail to complete a level. You should always get a score even if you fail, it just might be low.
- **Simplify variables**. You should only need to track one or two variables, not three or four (e.g. lives, moves, score, stage, etc). This is true of many well-designed mobile games (Tiny Wings has a score and an energy bar, Super Hexagon has a time and a progress status, Threes! just has a score, etc.).
- **Clear feedback**. It should be clear both throughout and at the end how actions translate into score, via feedback, preferably continual.

So here's my attempt. There are two primary variables, an energy bar and a score.
- **Energy**. Depleted a fixed amount by moving, gets a small boost when you eat a bit, which means exploring new areas is better than exploring old ones, and gets a large boost when you reach a target, which means you always start a stage with energy.
- **Score**. Small increment for eating a bit, large increment for completing a stage, and if you finish the final stage and have energy remaining, it goes into your score.

Note that these two are not themselves redundant! If you just have an energy that's converted to score at the end, then we can't give partial scores for failed levels, because ending with 0 energy = 0 score.

new-mechanics-2

cc @sofroniewn @andrewosh @sethvincent

### CODE REVIEW

**Comment by sofroniewn** [comment]
Key changes:
1) There is no longer a concept of lives, when you run out of moves / energy the level ends - you get a score and have to restart from the beginning.
2) "moves" are now represented with an energy bar rather than with a number
3) now a move along an unvisited path counts less than a move along an already visited path
4) your number of moves get a boost, but do not return all the way when you reach a target

After much thought (and a couple of rewrites of this post) - I think I'm ready to say goodbye to the lives. I liked the concept of lives because of the repetition that it forced (caused by dying and restarting the same place, but with the bits removed), but I disliked them because of the additional complexity they brought for the player and our analysis. There was also no reason why on any given level you should have one life, 3 lives, 10 lives, or infinite lives. I think very similar repetition could now come from just having the game over / score screen transition seamlessly into the start of the level again so people can replay it right away. Alternatively we could have stuck with our old version with the bits not coming back after death, death taking you to the last start location, and just given people infinitely many lives.

I'm worried the energy bar obfuscates the relevant variable of moves and that in general people will still not be sufficiently incentivized to find the shortest path - and they will just move around randomly until they get to the target - as we all seemed to do in your Morris style mazes (after the initial trial). I do like looking at the bar go down when I move, and up as I eat some bits.

The alternative approach is to have a very carefully chosen number of moves based on the maze, like the maze I made, (and in which you clearly learnt something very interesting) and expect that people will die many times.

In both these types of maze I think its important we consider what exactly performance variables we want to be tracking to look at learning - (moves/energy used or number of restarts till success etc.)

I don't really like the stages and number down at the bottom right, unclear what it is doing there, what it means - why isn't it showing 1/3 instead of just 1?

**Comment by freeman-lab** [comment]
@sofroniewn great thoughts and feedback! Overall I think we're synced on this, a couple replies:
- I'm also happy to say goodbye to lives, it's much simpler, and we don't lose much control. Totally agree we'll have fast restart upon failure, that'll be handled in `app`. Hopefully people will be driven to repeat to get a higher score / complete the level.
- In both style mazes, we always want to motivate people to finish in as few moves as possible. It's just about whether we more explicitly encourage higher and higher scores, or completing the level without dying. In my survey of the best mobile games, almost all emphasize the former.
- As is probably obvious, we can keep most of these changes but lock the number of moves more tightly by **turning remaining energy into score at the end of each stage and restoring energy completely at the end of each stage**. In other words, keep all the changes except (4). I just tried this, feels good, and might avoid across-stage analysis complexity. I just committed to this branch (though can easily revert). Does it feel better?

And totally agree we should think about analysis, but that it's also fine if the variables we expose are not exactly the ones we analyze (e.g. we could still analyze numbers of moves, not energy per se).

**Comment by freeman-lab** [comment]
One note about the change I just made: the dynamic range for scores is really good! For the toy test level, it still fells challenging (you can't wander around forever), but I was able to complete the level with anywhere from 8000 to 18000 points depending on my moves. I also like that score propagates across stages, but the constraints on movement stay encapsulated within each stage.

**Comment by sofroniewn** [comment]
Ok interesting, having your energy not return all the way after each stage might add to the tension / excitement, in a good way though that is lost if you get it all the way back after you reach a target. I'm still open to it just being a +50% boost say instead of a +100%. Might make analysis a bit weirder, but I think you felt really driven not to waste any moves, knowing that you wouldnt get them all back

**Comment by sofroniewn** [comment]
Now if you run out of energy you get a final score and have to restart the level from the beginning with zero points and all the dots there.

I just want to flesh out an alternative in a little more detail, if you run out of energy you could just restart from the last start point with the dots gone, same score (or your score could take a loss) and you keep playing. This way you'd have to repeat elements with the dots gone, wouldn't have to start from the beginning every time, and only get a final score if you decide to stop playing or if you complete the level.

I think this second option feels a bit strange. I don't like that you only get a score on voluntary exit or victory, and it weirdly mixes starting again from scratch and dying. Having to go back to the beginning every time might actually make it much cleaner, but now the number of times someone plays a level is an essential part of the analysis that used to be absorbed into the number of lives. Thoughts on this?

**Comment by freeman-lab** [comment]
Ok, re: the first point, I'll revert the last change then, wanted to try it out, but I agree the tension is nice! And we can always titrate the numbers to make it more or less constrained both within and across stages.

**Comment by andrewosh** [comment]
Cool changes! I like the idea of simplifying what was previously moves/score/lives. While there were a lot of variables to keep track of before, which at times could be confusing, I think that approach had a number of pros that could potentially be added to this version. Here are a few thoughts: 
1. Having the energy bar roll over from stage to stage could be exciting, but in our testing there were multiple times when we were tuning the number of available moves from stage to stage (i.e. the first stage was an "exploration" stage with a very high number of moves). We lose the ability to do this if energy persists across stages. Given that, we aren't just making the analysis more difficult, we're losing flexibility in level design. 
2. If energy were to not roll over, users should understand (at least approximately) how many moves they can make with their energy. If the energy bar rescales after each stage (a full bar represents a different number of moves), then it becomes very difficult to do any sort of planning just by looking at the bar (like @sofroniewn said). In the previous version, I could make a few bad moves and then say "I'm going to lose," even with many moves remaining. Players lose that level of detail now, which could be good or bad.
3. I feel like the bits also add confusion right now. If in making a move, I get back some energy that looks "something like half a move," it becomes even more unclear how many moves I have left. That can probably be tuned easily if some notion of scale (to fix point 2) is added. 
4. Should there be a discount factor when players replay the level multiple times? Your score of 18000 becomes more impressive if someone can't just replay the level (after having done done a substantial amount of learning on the first try) and get an 18000 as well. You'll say "but I did it on the first try" and your friends will say "yeah, sure." Hexaworld is very different from something like Super Meat Boy where to goal is to learn a complicated sequence of moves across multiple replays. We want to incentivize learning the maze as completely as possible, as quickly as possible. I wonder if you should only have one chance per level to shoot for that high score -- makes that first attempt more important and exciting.

Thoughts on any of that? Overall I love that the score becomes the focus here. Before, we were saying things like "we all did each stage in 5 or 6 moves," but it's a lot more fun to compare scores.

**Comment by freeman-lab** [comment]
Thanks @andrewosh ! A couple quick comments:

re: (1)
- I think we still have plenty of control, because we can control both the total energy and the amount that gets restored after stage completion (anywhere from 0% to 100%). Both could vary across levels and/or across stages.

re: (2) + (3)
- How about little gradation lines, maybe with one notch = one move, and a move with bits only drops half a notch. I still find the bar much more pleasing than a number, feels more engaging, and avoids too many numbers on the screen. Would that help? I can take a stab.

re: (4)
- My thinking is that replayability will be crucial to getting lots of data, so rather than discourage it, I'd ultimately much rather find clever ways to leverage randomization so that each run through a level feels fresh. But doing that well will take some thought.

**Comment by freeman-lab** [comment]
And re @sofroniewn, great to flesh out that other option, the two main things I like better about what's in this PR are (1) it was starting to get very confusing to incorporate failures / restarts when comparing performance, so as you say, it's "cleaner" this way, and (2) hoping for voluntary restarts seems weird, it feels more straightforward to kick someone out with a low score and hope they start again.

**Comment by freeman-lab** [comment]
@andrewosh just committed a change that adds notches to the energy bar, I think it's quite nice! At least in this version, a move with bits loses one notch, and a move with no bits loses two, so it's pretty obvious for planning purposes. After testing a few variants this felt the best.

notches

I think this addresses many of your concerns. Still very on the fence about whether energy should be fully restored at the end of a stage! I've left it in for now.

**Comment by sofroniewn** [comment]
I'm really liking the discrete energy bar - one unit is a move along an un-visited path, two units is a move along a visited path. If we go to smaller / larger mazes could have a smaller / larger energy bar while keeping that rule the same

**Comment by sofroniewn** [comment]
Re @andrewosh  - I think your point (4) is a really important one, we need to keep track of how many plays someone has done - and in fact really want people to keep replying each one to get to expert level, not sure that full randomization @freeman-lab is what we want (or even permuting colors every time) but instead might want to have careful probe trials to determine wether they have over learnt a sequence of actions or built up a map

**Comment by sofroniewn** [comment]
I'm still on the fence about the replenishing of the energy bar all the way after each target reach. I'm currently thinking no as it adds more difficulty / excitement, but it maybe makes us want to analyze each play as a unit (till victory / death) and look at learning across multiple plays instead of each stage as a unit and learning across multiple stages. Might be easier for our analysis to think about the former instead of the latter

**Comment by freeman-lab** [comment]
@sofroniewn @andrewosh agreed, I guess I didn't mean full randomization, just enough random elements or probes or something that make replaying the same level interesting, and let us track behavior over multiple replays. I've wanted this for myself to make my own replays more interesting!

**Comment by sofroniewn** [comment]
@freeman-lab - did some more play testing - I'm coming around to the idea of the energy bar not refilling all the way after reaching a target - it makes the moves more precious, and feel like the different stages are connected to each other, rather than just like "oh here we go again" after each time you restart

**Comment by sofroniewn** [comment]
I think the stages should be represented pictorially with unfilled circles that fill up each time you reach a target. Having them unfilled lets you know how many there are to begin with, and also makes it a little more clear what the objective is. These circles can be underneath the score number, allowing us to get rid of everything below the outer ring

**Comment by freeman-lab** [comment]
@sofroniewn interesting idea, just mocked it (desktop and mobile). I didn't like it under the score, top gets too busy, and having something at the bottom frames the play area nicely.

screen shot 2015-12-25 at 11 22 08 pm

Only cons I see (compared to a stage number):
- I want the option to make the number of stages unknown (e.g. a play till you die style), especially with energy carrying over that could be a fun style, and could do that this way, just without the empty circles, but then the circles will start appearing out of nowhere.
- Will it be clear that the circles getting filled in are not related to collecting bits?
- Does this look too much like the bars? Some visual similarity is good, too much becomes confusing.

**Comment by freeman-lab** [comment]
For comparison, here's the layout I'm now thinking for the single stage number. I'm happy making it a `1/N` btw for the times we want to indicate the total number.

screen shot 2015-12-25 at 11 37 39 pm

**Comment by sofroniewn** [comment]
@freeman-lab - at the bottom looks good for the dots, maybe on the left hand side though so it aligns with the energy bar.

I love the idea of play till you die, agree with energy bar not refilling it becomes more interesting, and agree way to do that easily is without the empty circles. Not sure we'd need to indicate the circles at all then or have any numbers.

I think it will be clear the filling of the circles corresponds to the reaching of the targets with the proper use of animations.

I think they look ok - different enough from the bars

But i'm really coming around to this play till you die idea, just have to make sure it really is getting harder as you go - could be important to introduce another mechanic like time pressure from getting chased to ensure that

**Comment by sofroniewn** [comment]
Ok looking at the new post now - I like the stages with the 1/5 - quite elegant

**Comment by sofroniewn** [comment]
Worth thinking about a fun way to not have stages, but just a play till you die, and the energy bar runs down and maybe you get chased too and chasing gets faster as you go further along in the level

**Comment by freeman-lab** [comment]
Yup, totally with you, pressure would have to go up, could do simply with what we have just by adding a decay to energy that ramps up over time. Can try on another branch once this is done.

Still think some indication of stage / progress through stages will be useful though, even just to give you a qualitative sense of how far you've made it.

**Comment by sofroniewn** [comment]
Ok - looking at both circles vs stage x/n, I'm sort of leaning towards stage x/n right now, just one less thing to explain, one less potentially confusing visual element

**Comment by freeman-lab** [comment]
Ok, new stages layout implemented, I quite like it now. Last thing to decide for this PR is whether to have carry-over, I'm still on the fence! Need one more night's sleep on it. There's a lot I like, but my main concern: it has less score dynamic range than a version where energy -> points after each stage. We can tweak the numbers around, but fundamentally, because you can't have more than 100% energy, if we use carry-over, there's a hard cap on how much "score bonus" you can accumulate, and that cap limits the dynamic range.

**Comment by sofroniewn** [comment]
image

Layout not working in mine - energy bar and score on different lines

**Comment by sofroniewn** [comment]
Agreed with the less dynamic range - but the flip side comes if we move to a regime that is play till you die, then score becomes more dependent on the number of stages you progress through, and it might make more sense to have energy bar carry over

**Comment by freeman-lab** [comment]
Ok, I found a solution. What I liked about the carry-over was the sense of continuity and that playing well early helped you later on. What I didn't like was the very indirect relationship between remaining moves and score, which was only realized at the end, and would have become meaningless in play-till-you-die anyway (by definition, ending with no energy = no score bonus). 

So I just combined the two. When you complete a stage, you get a score boost based on your remaining energy, and your energy refills to what it was plus a small boost, i.e. it carries over. This also now trivially reduces to one extreme (if we get rid of that intermediate score boost) or the other (if we refill to 100%), each a one line change.

We can continue to experiment, but I'm happy with how this plays now, and think we should merge it in.

**Comment by sofroniewn** [comment]
I like what you're trying to accomplish, and am glad its easy to switch around in the code, but I find it a bit odd that the bar goes all the way down to zero and then goes back up to this height that depends on how much of the bar was left. To me to continuity is broken when the energy bar hits zero. Maybe just make the bar flash as the extra points get added and not have them drain down?

**Comment by freeman-lab** [comment]
Cool, good idea, I like this quite a lot now.

**Comment by sofroniewn** [comment]
Better - should the energy bar drain on the final time you reach the target when the level is complete or would that now be inconsistent?

**Comment by freeman-lab** [comment]
I think one visual cue should mean "energy -> score", either flashing or draining, but not both. If we want to keep the draining, then we could use some other visual element to make clear that your energy stays where it is even though what's left is being added to your score. But I kinda like the flashing, matches the flashing on the ring.

**Comment by sofroniewn** [comment]
Fair enough - the flashing of the energy occurs at a slight delay and higher frequency to the flashing of the ring, might want to tweak the times slightly (slower blinking of the energy bar) to make it more clear what is happening - otherwise looks good to merge

**Comment by sofroniewn** [comment]
Instead of stage 1 of 3, could be 1 of 3 collected - or just 1 collected, the idea being you have to collect the large white circles

**Comment by freeman-lab** [comment]
Changed `stage 1/N` to `1/N found`, and tweaked the flashing so one flash = one remaining move turned into score bonus. Delay was intentional, so eye is drawn first to the flashing, then the bar/score, rather than all at once, but I slowed the bar flashing down. Going to merge as is, can try adding an explicit numerical move counter in a follow-up change.

**Pull request merged**
